export enum API_URL {
    HOST = "http://vroteam.online:6068",
    LOGIN = "users/login",
    REGISTER = "users/register",
    REFRESH_TOKEN = "users/refreshtoken",
    GET_USER_INFO = "users/profile",
    GET_ALL_USERS = "Admin/all-user",
    USER_STATISTIC = "Admin/statistic-account-management",
    BLOCK_USER = "Admin/block-user",
    GET_SKETCHS = "Admin/all-product",
    OVERVIEW_STATISTIC = "Admin/overview-statistic",
    STATISTIC_SKETCH = "Admin/statistic-products",
    OVERVIEW_STATISTIC_DAY = "Admin/overview-statistic-day",
    OVERVIEW_STATISTIC_MONTH = "Admin/overview-statistic-month",
    OVERVIEW_STATISTIC_QUARTER = "Admin/overview-statistic-quarter",
    OVERVIEW_STATISTIC_YEAR = "Admin/overview-statistic-year",
    GET_ALL_REPORT = "Admin/statistic-report",
    STATISTIC_REPORT = "Admin/statistic-report",

}